apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: mcp
    app.kubernetes.io/name: cyclops-mcp
    app.kubernetes.io/part-of: cyclops
  name: cyclops-mcp
  namespace: cyclops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: mcp
    app.kubernetes.io/name: cyclops-mcp
    app.kubernetes.io/part-of: cyclops
  name: cyclops-mcp
  namespace: cyclops
rules:
  - apiGroups:
      - 'cyclops-ui.com'
    resources:
      - '*'
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: mcp
    app.kubernetes.io/name: cyclops-mcp
    app.kubernetes.io/part-of: cyclops
  name: cyclops-mcp
  namespace: cyclops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cyclops-mcp
subjects:
  - kind: ServiceAccount
    name: cyclops-mcp
    namespace: cyclops
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cyclops-mcp
  namespace: cyclops
  labels:
    app: cyclops-mcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cyclops-mcp
  template:
    metadata:
      labels:
        app: cyclops-mcp
    spec:
      serviceAccountName: cyclops-mcp
      containers:
        - name: cyclops-mcp
          image: cyclopsui/cyclops-mcp:v0.1.0
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: cyclops-mcp
  namespace: cyclops
  labels:
    app: cyclops-mcp
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: cyclops-mcp
